In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32) 
print(a.ndim, a.shape, a.dtype ) 


2 (2, 3) float32


In [ ]:
np.ones((3,4),dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
np.zeros((3,4),dtype=np.float32)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [ ]:
np.full((3,4), 3.14, dtype=np.float32) # fill the array with certain value 3.14


array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]], dtype=float32)

In [ ]:
np.eye(3, dtype=np.float32) # this creates an identity matrix of size 3x3 with float32 data type

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
np.random.rand(3,4).astype(np.float32)# this creates a 3x4 array of random numbers between 0 and 1, and then converts it to float32 data type

array([[0.5903311 , 0.15661329, 0.11334706, 0.5445981 ],
       [0.9624635 , 0.49781594, 0.4359254 , 0.29999653],
       [0.60895747, 0.65285945, 0.6112532 , 0.7236622 ]], dtype=float32)

In [ ]:
b = np.array([[1,2,3],[4,5,6]],dtype=np.float32)# this creates a 2x3 array of float32 data type with the specified values
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
np.arange(0,10,2) # this creates an array of numbers from 0 to 10 (exclusive) with a step of 2

array([0, 2, 4, 6, 8])

In [ ]:
A=np.ones((2,3),dtype=np.float32)
B=np.zeros((4,3),dtype=np.float32)
np.concatenate((A,B),axis=0) # this concatenates the two arrays A and B along the first axis (rows), resulting in a new array with shape (4,3) where the first two rows are from A and the next two rows are from B

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
a=np.ones((2,3),dtype=np.float32)
b=np.zeros((2,3),dtype=np.float32)
print(np.concatenate((a,b),axis=1))# this concatenates the two arrays a and b along the second axis (columns), resulting in a new array with shape (2,6) where the first three columns are from a and the next three columns are from b.
print(np.concatenate((a,b),axis=0))
print(a+b)# this adds the two arrays a and b element-wise, resulting in a new array where each element is the sum of the corresponding elements in a and b. Since a is an array of ones and b is an array of zeros, the result will be an array of ones with the same shape as a and b.

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
x=np.array((5,6),dtype=np.float32)
print(x.astype(np.int32))# this converts the array x from float32 data type to int32 data type, resulting in a new array with the same values but a different data type. The values will be truncated to integers, so the result will be an array with values [5, 6] of type int32.

[5 6]


In [ ]:
a=np.ones((2,2,3))# this creates a 3D array of shape (2,2,3) filled with ones. The first dimension has size 2, the second dimension has size 2, and the third dimension has size 3. The resulting array will have a total of 2*2*3 = 12 elements, all initialized to one.
print(a.ndim, a.shape, a.dtype )
b=np.zeros_like(a)# this creates a new array with the same shape and data type as the array a, but filled with zeros. The resulting array will have the same dimensions and size as a, but all elements will be initialized to zero.
print(b.ndim, b.shape, b.dtype )

3 (2, 2, 3) float64
3 (2, 2, 3) float64


In [ ]:
np.random.random((10,3))

array([[0.23715364, 0.12194199, 0.60915344],
       [0.67614027, 0.1871427 , 0.85268487],
       [0.56152607, 0.0722426 , 0.04995018],
       [0.47610446, 0.1470957 , 0.05216583],
       [0.89723184, 0.80321985, 0.72433638],
       [0.49327508, 0.8777115 , 0.37874093],
       [0.20015838, 0.36241216, 0.89064956],
       [0.47797896, 0.29140427, 0.80589868],
       [0.65831844, 0.16760815, 0.09255455],
       [0.3654886 , 0.40808137, 0.94195537]])

In [ ]:
np.random.seed(42)# this sets the random seed to 42, which ensures that the random numbers generated by numpy will be the same every time the code is run. This is useful for reproducibility and debugging purposes, as it allows you to get the same random numbers each time you run the code.
print(np.random.random((10,3)))# this generates a 10x3 array of random numbers between 0 and 1, using the random seed that was set to 42. The resulting array will contain the same random numbers every time the code is run, due to the fixed seed.

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]


In [ ]:
# Create arrays with specific values
zeros = np.zeros((3, 4))           # 3x4 array of zeros
ones = np.ones((2, 2))             # 2x2 array of ones
arange = np.arange(10)             # [0, 1, 2, ..., 9]
lin = np.linspace(0, 1, 5)         # [0., 0.25, 0.5, 0.75, 1.] the linspace function creates an array of 5 evenly spaced values between 0 and 1
random = np.random.random((3, 3))  # Random values between 0 and 1
# Create arrays like existing ones
zeros_like = np.zeros_like(a)
ones_like = np.ones_like(a)
# Concatenation
b = np.array([[7,8,9]])
#c = np.concatenate([a, b], axis=0)  # Stack vertically


In [ ]:
a= np.array([1,2,3,4,5,6])
print(a.reshape(3, 2))   # Reshape to 3x2
print(a.reshape(2, -1))  # -1 infers size: becomes 2x3
print(a.ravel())         # Flatten to 1D: [1,2,3,4,5,6]
print(a.flatten())       # Returns a copy (ravel returns view) 


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
a= np.arange(10).reshape(5, 2)  # 5x2 array
print(a.T)                       # Transpose: 2x5
print(a.transpose((1, 0)))       # Same as .T


[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
arr= np.array([1, 2, 3, 4])
for element in arr:
    print(element)


1
2
3
4


In [ ]:
#itrate over a multi-dimensional  array
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Iterate over rows
for row in matrix:
    print("Row:", row)

# Using nditer (efficient iteration)
for element in np.nditer(matrix):
    print(element)

# Iterate with indices
for index, value in np.ndenumerate(matrix):
    print(f"Index {index}: {value}")


Row: [1 2]
Row: [3 4]
Row: [5 6]
1
2
3
4
5
6
Index (0, 0): 1
Index (0, 1): 2
Index (1, 0): 3
Index (1, 1): 4
Index (2, 0): 5
Index (2, 1): 6


In [ ]:
#Vectorized Operations (Preferred over loops)
# Instead of looping:
arr = np.array([1, 2, 3, 4, 5])
squared = arr ** 2  # Vectorized: [1, 4, 9, 16, 25]

# Instead of:
result = np.empty_like(arr)
for i in range(len(arr)):
    result[i] = arr[i] * 2
# Use:
result = arr * 2
print(result)  # [2, 4, 6, 8, 10]


[ 2  4  6  8 10]


In [ ]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)   # Addition: [5, 7, 9]
print(a - b)   # Subtraction: [-3, -3, -3]
print(a * b)   # Multiplication: [4, 10, 18]
print(a / b)   # Division: [0.25, 0.4, 0.5]
print(a ** 2)  # Power: [1, 4, 9]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [ ]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
a<b  # Element-wise comparison: [True, True, True]


array([ True,  True,  True])

In [ ]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
# In-place division: a becomes [0.25, 0.4, 0.5]
print(a/b)  # [0.25, 0.4, 0.5]


[0.25 0.4  0.5 ]


In [ ]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)  # 1*4 + 2*5 + 3*6 = 32
print(dot_product)          # Output: 32


32


In [36]:
# Matrix Multiplication (2D arrays)
A = np.array([[1, 2], [3, 4]])  # 2x2
B = np.array([[5, 6], [7, 8]])  # 2x2
# Method 1: np.dot()
C = np.dot(A, B)
# [[1*5+2*7, 1*6+2*8],
#  [3*5+4*7, 3*6+4*8]] = [[19, 22], [43, 50]]
# Method 2: @ operator (Python 3.5+)
D = A @ B  # Same result
# Method 3: np.matmul()
E = np.matmul(A, B)  # Same result
print(C)  # [[19, 22], [43, 50]]
print(D)  # [[19, 22], [43, 50]]
print(E)  # [[19, 22], [43, 50]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [37]:
# matrix-vector multiplication
M = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
v = np.array([7, 8])                    # 2-element vector
result = M @ v  # Results in 3-element vector
# [1*7+2*8, 3*7+4*8, 5*7+6*8] = [23, 53, 83]
print(result)  # [23, 53, 83]


[23 53 83]


In [38]:
# Matrix Properties and Operations
# Identity matrix
I = np.eye(3)  # 3x3 identity
# Matrix transpose
A = np.array([[1, 2, 3], [4, 5, 6]])
A_T = A.T
# Matrix inverse
square_matrix = np.array([[4, 7], [2, 6]])
inv = np.linalg.inv(square_matrix)# this computes the inverse of the square matrix using numpy's linear algebra module. 
# Determinant
det = np.linalg.det(square_matrix)# this computes the determinant of the square_matrix using numpy's linear algebra module. 
print("Identity Matrix:\n", I)
print("Transpose of A:\n", A_T)
print("Inverse of square_matrix:\n", inv)
print("Determinant of square_matrix:", det)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]
Inverse of square_matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Determinant of square_matrix: 10.000000000000002


In [ ]:
arr= np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# Single element
print(arr[0, 0])     # First element: 1
# Slicing
print(arr[0, :])     # First row: [1, 2, 3, 4]
print(arr[:, 0])     # First column: [1, 5, 9]
print(arr[1:, 2:])   # Bottom-right 2x2: [[7, 8], [11, 12]]


1
[1 2 3 4]
[1 5 9]
[[ 7  8]
 [11 12]]


In [ ]:
#Boolean indexing
mask = arr > 5
print(arr[mask])     # Elements > 5: [6, 7, 8, 9, 10, 11, 12]
# Fancy indexing
print(arr[[0, 2], [1, 3]])  # Elements at (0,1) and (2,3): [2, 12]


[ 6  7  8  9 10 11 12]
[ 2 12]


In [33]:
a.sum() # sum all entries 
a.sum(axis=0) # sum over rows 
#a.sum(axis=1) # sum over columns 
#a.sum(axis=1, keepdims=True) 


6

In [ ]:
#Adding scalar to array
arr = np.array([1, 2, 3])
print(arr + 10)  # [11, 12, 13]
# Adding vector to matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 3x3
vector = np.array([10, 20, 30])                        # 3 elements
result = matrix + vector  # Adds vector to each row
# [[11, 22, 33],
#  [14, 25, 36],
#  [17, 28, 39]]
# Broadcasting rules example
A = np.ones((2, 3, 4))  # 2x3x4 3D array
B = np.ones((3, 4))     # 3x4
C = A + B  # Works! B broadcasts to shape (1,3,4) then (2,3,4)


[11 12 13]


In [35]:
# SLOW: Python loop
def slow_sum(arr):
    total = 0
    for i in range(len(arr)):
        total += arr[i]
    return total
# FAST: NumPy vectorization
def fast_sum(arr):
    return arr.sum()
# Timing comparison (for large arrays):
large_arr = np.random.rand(1000000)
# slow_sum: ~100ms
# fast_sum: ~1ms (100x faster!)
